#! /bin/bash
set -e

if [ `uname` = "Darwin" ]
then
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I TEST -P 4 sh -c "run TEST"
else
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I TEST -P 4 -I {} echo `if [ "$CGO_ENABLED" = "1" ]; then go test -race {}; else go test {}; fi`
fi
