#! /bin/bash
set -e

run () {
    if [ "$CGO_ENABLED" = "1" ]
    then
      exec go test -race $1
    else
      exec go test $1
    fi
    return 0
}
export -f run

if [ `uname` = "Darwin" ]
then
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I TEST -P 4 sh -c "run TEST"
else
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I TEST -P 4 echo $(run TEST)
fi
